Feature see unread messages count
jpascual1994/TargetMVD pull request #30
Opened 2017-10-18 18:20 UTC by jpascual1994

This PR includes:
- Show number of unread messages

Trello card: https://trello.com/c/UBwtwawu/14-3-as-a-user-i-should-be-able-to-see-the-unread-conversations-count-so-i-can-easily-identify-them

![captura de pantalla 2017-10-18 a la s 15 18 34](https://user-images.githubusercontent.com/30729697/31735231-a82b7cbe-b417-11e7-9eec-b5b839449594.png)

2017-10-18 18:38 UTC, mdornel requested changes

2017-10-18 18:38 UTC, mdornel commented on app/assets/javascripts/users.js.erb
> +function readMessages(chatId) {
Not sure why you're using `chatId` here. I don't see  `chatId` on the function

2017-10-18 18:38 UTC, mdornel commented on app/models/chat.rb
> +    messages.where(to: user_id, read: false)
You can create a scopes on your `Message` model and then chain them here.

```
scope :to_user, ->(user_id) { where(to_id: user_id) }
scope :unread, -> { where(read: false) }
```

Then you can do `messages.to_user(user_id).unread`

2017-10-18 18:52 UTC, MaicolBen approved these changes

2017-10-18 19:02 UTC, gabrielrp requested changes

2017-10-18 19:02 UTC, gabrielrp commented on app/views/users/_matches_list.html.haml
> +          .unread-msgs{ class: ('hidden' if match.chat.unread_messages_count(user.id) == 0) }
In order to check whether a associations collection is empty or not, it's better to use the `exists?` method in this case, due to the fact that it won't trigger a `count` on the DB. Instead, the `exists?` method will use `LIMIT 1`, which is faster. So, make `unread_messages` public, and use it here: 
`.unread-msgs{ class: ('hidden' unless match.chat.unread_messages(user.id).exists?) }`

You should read the following article, it explains how `empty?`, `any?`, `blank?` and `exists?` work.
http://andreigridnev.com/empty-blank-any-exists-methods-of-ruby-on-rails-activerecord/

2017-10-18 19:30 UTC, gabrielrp approved these changes

2017-10-19 14:02 UTC, mdornel approved these changes

2017-10-19 14:02 UTC, merged