Feature Facebook sign in
jpascual1994/TargetMVD pull request #7
Opened 2017-09-04 15:45 UTC by jpascual1994

This PR includes:
- Sign in with facebook and tests

2017-09-04 17:37 UTC, gabrielrp requested changes

2017-09-04 17:37 UTC, gabrielrp commented on app/models/user.rb
> +        user.gender = FACEBOOK_GENDERS[auth.extra.raw_info.gender]
Declare `gender` as `enum` and then check if the facebook gender matches any of ours.

2017-09-04 17:37 UTC, gabrielrp commented on app/models/user.rb
> +        user.gender = FACEBOOK_GENDERS[auth.extra.raw_info.gender]
Also, write it in one line, something like `user.gender = genders.key(auth.extra.raw_info.gender) ? auth.extra.raw_info.gender : 'others'`

2017-09-04 18:03 UTC, mdornel requested changes

2017-09-04 18:03 UTC, mdornel commented on config/initializers/devise.rb
> +  config.omniauth :facebook, '1957979147801504', '6e06570424d211750ca738deb028a9ee',
You shouldn't publish your keys in github, this is private data. Use `figaro` gem instead (check https://github.com/laserlemon/figaro)

You should create a file using the gem, for example:
```
# config/application.yml

FACEBOOK_APP_ID: "YOUR_APP_ID"
FACEBOOK_APP_KEY: "YOUR_FACEBOOK_APP_KEY"
```

And use it as: `ENV['FACEBOOK_APP_ID']`

2017-09-04 18:03 UTC, mdornel commented on spec/features/facebook_log_in_spec.rb
> +      visit '/users/auth/facebook'
Here you can use the path helper for this route.

2017-09-04 18:03 UTC, mdornel commented on spec/features/facebook_log_in_spec.rb
> +      visit '/'
Here too.

2017-09-05 14:03 UTC, mdornel approved these changes

2017-09-05 15:37 UTC, gabrielrp requested changes

2017-09-05 15:37 UTC, gabrielrp commented on spec/support/omniauth_macros.rb
> +  def valid_response()
The parentheses aren't necessary

2017-09-05 15:37 UTC, gabrielrp commented on spec/support/omniauth_macros.rb
> +  def set_valid_omniauth(opts = {})
Where do you use the `opts` param?

2017-09-05 15:37 UTC, gabrielrp commented on spec/support/omniauth_macros.rb
> +  def set_invalid_omniauth(opts = {})
Same^

2017-09-05 15:37 UTC, gabrielrp commented on spec/features/facebook_log_in_spec.rb
> +      set_valid_omniauth()
Parentheses aren`t necessary

2017-09-05 15:37 UTC, gabrielrp commented on spec/features/facebook_log_in_spec.rb
> +      set_invalid_omniauth()
Same^

2017-09-05 15:37 UTC, gabrielrp commented on spec/features/facebook_log_in_spec.rb
> +      expect(page).to have_content( User.last.name)
Remove extra space

2017-09-06 16:34 UTC, gabrielrp approved these changes

2017-09-06 16:34 UTC, merged